// exports.getAddress = require("./get-address")
exports.exists = require("./exists");
exports.listAuctions = require("./list-auctions");
exports.startNewAuction = require("./start-new-auction");
exports.cancelAuction = require("./cancel-auction");
exports.liquidateAuction = require("./liquidate-auction");
exports.bid = require("./bid");
exports.setAuctionDealId = require("./set-auction-dealid");
exports.bal = require("./bal");
